[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste="1.0.9"
lazy_static="1.4.0"
iter_tools="0.1.4"